# Site settings
title: The Midnight Talker
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ici sont évoqués les véritables trésors cachés de la pop culture
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pepesedona
github_username:  juanpeter

# Build settings
markdown: kramdown
